# Generated by Django 3.2.4 on 2021-06-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasyCartUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('city', models.CharField(max_length=15)),
            ],
        ),
    ]
