# Generated by Django 3.2.4 on 2021-06-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_testapp', '0002_easycartusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasyCartUsersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('mobileNo', models.IntegerField()),
                ('city', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='EasyCartUsers',
        ),
    ]
