# Generated by Django 3.2.4 on 2021-06-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_testapp', '0003_auto_20210614_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=20)),
                ('mobileNo', models.IntegerField()),
                ('city', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
