# Generated by Django 3.2.4 on 2021-06-17 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_testapp', '0005_easycart_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasyCartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfCategory', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='demo_testapp.easycartcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EasyCartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfProduct', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_testapp.easycartcategory')),
            ],
        ),
    ]
