# Generated by Django 3.2.4 on 2021-06-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_testapp', '0006_easycartcategory_easycartproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EasyCartCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='EasyCartProduct',
            new_name='Product',
        ),
    ]
