# Generated by Django 3.2.4 on 2021-06-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_testapp', '0009_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='picture/'),
        ),
    ]
